### ISSUE TITLE
Cannot compile

### ISSUE THREAD

**Issue by Ironfist-error** [jkoppel/project-ironfist#133]
I can't compile Ironfist, got MSB6006 error, line 209:

```
<CustomBuild
      Sources                     ="@(CustomBuild)"
      BuildSuffix                 ="$(_BuildSuffix)"

      TrackerLogDirectory         ="%(CustomBuild.TrackerLogDirectory)"
      MinimalRebuildFromTracking  ="%(CustomBuild.MinimalRebuildFromTracking)"

      TLogReadFiles               ="@(CustomBuildTLogReadFiles)"
      TLogWriteFiles              ="@(CustomBuildTLogWriteFiles)"
      TrackFileAccess             ="$(TrackFileAccess)"
      ToolArchitecture            ="$(CustomBuildToolArchitecture)"
      TrackerFrameworkPath        ="$(CustomBuildTrackerFrameworkPath)"
      TrackerSdkPath              ="$(CustomBuildTrackerSdkPath)"

      AcceptableNonZeroExitCodes  ="%(CustomBuild.AcceptableNonZeroExitCodes)"
      >
    </CustomBuild> 
```

**Comment by jkoppel** [comment]
Hello,

I think you accidentally pasted something from the wrong tab of Visual Studio. Could you go to the "Errors" tab and find the actual error message? "MSB6006, line 209" means nothing to me.

**Comment by Ironfist-error** [comment]
I have all necessary files. I also didn't change anything in the original code. I did everything according to the guide from project ironfist wiki. I also don't know what do you mean by "Look at the custom build step and make sure the paths are set up correctly.". I must change something in code before compiling?

**Comment by jkoppel** [comment]
Both editor.asm and heroes2.asm have custom build steps set up to run ml.exe, the Microsoft Macro Assembler (MASM), on them. The error you're getting is from the custom build step for editor.asm . Right click on editor.asm and look at the custom build step. The command it defines should make sense.

Hmmm.....now that I think about it, the likely cause is not you missing editor.asm, but missing MASM. This is not included in all Visual Studio installations.

**Comment by Ironfist-error** [comment]
OK, I found solution. All I had to do was tick "MASM" option in Build Customization.

But now I have different problem:

`1>------ Kompilacja rozpoczęta: Projekt: ironfist_vs, Konfiguracja: Debug Win32 ------
2>------ Kompilacja rozpoczęta: Projekt: editor_vs, Konfiguracja: Debug Win32 ------
1>adv.obj : warning LNK4075: zignorowano opcję „/EDITANDCONTINUE” z powodu określenia opcji „/OPT:ICF”
2>Debug\editor.obj : warning LNK4042: obiekt określono więcej niż raz; dodatkowe wystąpienia zostały zignorowane
1>libucrtd.lib(87tran.obj) : error LNK2005: Element __rtforexpinf jest już zdefiniowany w elemencie heroes2.obj
2>editor.obj : error LNK2019: nierozpoznany zewnętrzny symbol "void * __cdecl CopyMap(void)" (?CopyMap@@YAPAXXZ) przywołany w funkcji "public: __thiscall editManager::editManager(void)" (??0editManager@@QAE@XZ)
1>..\..\..\build\bin\ironfist.exe : fatal error LNK1169: znaleziono co najmniej jeden wielokrotnie zdefiniowany symbol
2>editor.obj : error LNK2019: nierozpoznany zewnętrzny symbol "public: void __thiscall editManager::InitializeMap(int,int,int)" (?InitializeMap@editManager@@QAEXHHH@Z) przywołany w funkcji "public: virtual int __thiscall editManager::Open(int)" (?Open@editManager@@UAEHH@Z)
2>editor.obj : error LNK2019: nierozpoznany zewnętrzny symbol "void __fastcall ShowErrorMessage(char const *)" (?ShowErrorMessage@@YIXPBD@Z) przywołany w funkcji _sub_401AD9
2>overlay.obj : error LNK2001: nierozpoznany symbol zewnętrzny "void __fastcall ShowErrorMessage(char const *)" (?ShowErrorMessage@@YIXPBD@Z)
2>editor.obj : error LNK2019: nierozpoznany zewnętrzny symbol "public: void __thiscall editManager::SpellScrollEditDialog(int *)" (?SpellScrollEditDialog@editManager@@QAEXPAH@Z) przywołany w funkcji _eventsManager__Main
2>editor.obj : error LNK2019: nierozpoznany zewnętrzny symbol "int __fastcall SpellScrollEditDialogCallback(struct tag_message &)" (?SpellScrollEditDialogCallback@@YIHAAUtag_message@@@Z) przywołany w funkcji "public: void __thiscall editManager::SpellScrollEditDialog_orig(int *)" (?SpellScrollEditDialog_orig@editManager@@QAEXPAH@Z)
2>editor.obj : error LNK2019: nierozpoznany zewnętrzny symbol "int __cdecl WinConditionHandler(void)" (?WinConditionHandler@@YAHXZ) przywołany w funkcji _sub_41C370
2>editor.obj : error LNK2019: nierozpoznany zewnętrzny symbol "int __fastcall FillInWinCondition(int)" (?FillInWinCondition@@YIHH@Z) przywołany w funkcji "int __cdecl WinConditionHandler_orig(void)" (?WinConditionHandler_orig@@YAHXZ)
2>editor.obj : error LNK2019: nierozpoznany zewnętrzny symbol "public: void * __thiscall fullMap::Clone(class fullMap *)" (?Clone@fullMap@@QAEPAXPAV1@@Z) przywołany w funkcji _editManager__Main
2>..\..\..\build\bin\editor.exe : fatal error LNK1120: liczba nierozpoznanych elementów zewnętrznych: 8
2>Kompilowanie projektu „editor_vs.vcxproj” wykonane — NIEPOWODZENIE.
1>Kompilowanie projektu „ironfist.vcxproj” wykonane — NIEPOWODZENIE.
========== Kompilacja: 0 zakończono powodzeniem, 2 zakończono niepowodzeniem, 0 zaktualizowano, 0 pominięto =========`

**Comment by Ironfist-error** [comment]
I already had Debug option, not Release,

**Comment by jkoppel** [comment]
I looked a little closer at the error message.

It looks like it's building editor.asm and nothing else. The set of symbols it can't find are exactly the ones defined in the rest of the project ( https://github.com/jkoppel/project-ironfist/blob/master/src/asm/editor_imports.inc ). Perhaps the option you ticked was causing it to not build the rest of the program.

**Comment by jkoppel** [comment]
Ah. Those files are actually not included in compilation. Visual Studio doesn't see them, because they're part of a custom build step, not VS's built-in build process. I meant that it seems to not be compiling the actual .cpp files, which define the relevant symbols.

I apologize for my brevity. I want you to succeed in modding H2, and I'll be better able to help after my huge deadline on next Saturday.
