### ISSUE TITLE
Possible bug in share vision?

### ISSUE THREAD

**Issue by chrisbigart** [jkoppel/project-ironfist#8]
I'm attaching a save game I was playing in the original h2 that I opened in ironfist.  The map setup is the human player (blue) vs an enemy alliance of all other colors, but upon ending my turn I am granted vision of enemy hero movement.

[champion2_m3w2d5.zip](https://github.com/jkoppel/project-ironfist/files/232550/champion2_m3w2d5.zip)

**Comment by chrisbigart** [comment]
```
  for (int i = 0; i < NUM_PLAYERS; i++) {
    if (this->sharePlayerVision[player][i]) 
```
The entire `sharePlayerVision` array seems to be populated with the value of `205` when stepping through this in the debugger, I don't know what that means.

**Comment by jkoppel** [comment]
Thanks. I think I know what's wrong and will add this to Trello.

**Comment by chrisbigart** [comment]
Can you send me an invite to the Trello page?  Thanks

**Comment by jkoppel** [comment]
Added you :)

**Comment by XT3RM1N8R** [comment]
Should this be closed now?
